In [1]:
import numpy as np

In [2]:
# 1
a_1 = np.arange(1,11)
print(f"First task result:\n{a_1}\n")

First task result:
[ 1  2  3  4  5  6  7  8  9 10]



In [3]:
#2
m_2 = np.zeros((3, 3), dtype=int)
print(f"Second task result:\n{m_2}\n")

Second task result:
[[0 0 0]
 [0 0 0]
 [0 0 0]]



In [4]:
#3
m_3 = np.random.randint(1, 11, size=(5, 5))
print(f"Third task result:\n{m_3}\n")

Third task result:
[[ 8  4  9  3  1]
 [ 3  8  1 10  6]
 [ 6  3  6  3  6]
 [ 5  7  4  8  6]
 [ 8  7 10  9 10]]



In [5]:
#4
m_4 = np.random.random((4,4))
print(f"Fourth task result:\n{m_4}\n")

Fourth task result:
[[0.88531463 0.83226359 0.8158358  0.7704637 ]
 [0.24096398 0.46798953 0.13975376 0.80800182]
 [0.15349897 0.09411576 0.35623085 0.12157274]
 [0.44812777 0.081343   0.14136507 0.84074688]]



In [6]:
#5
a_5 = np.random.randint(1, 11, size=5)
b_5 = np.random.randint(1, 11, size=5)

sum_array = a_5 + b_5
subtr_array = a_5 - b_5
prod_array = a_5 * b_5

print(f"""Fifth task results:
      First array  = {a_5};
      Second array = {b_5};
      
      Sum           = {sum_array};
      Subtraction   = {subtr_array};
      Prod          = {prod_array}\n""")

Fifth task results:
      First array  = [8 9 9 6 9];
      Second array = [ 2  5 10  5 10];
      
      Sum           = [10 14 19 11 19];
      Subtraction   = [ 6  4 -1  1 -1];
      Prod          = [16 45 90 30 90]



In [7]:
#6
a_7 = np.random.randint(1, 11, size=7)
b_7 = np.random.randint(1, 11, size=7)

dot_prod = np.dot(a_7, b_7)
print(f"""Sixth task results:
      First array  = {a_7};
      Second array = {b_7};
      Result = {dot_prod}\n""")

Sixth task results:
      First array  = [8 8 3 6 9 9 4];
      Second array = [10  6  7  9  8  1  6];
      Result = 308



In [8]:
#7
m_7 = np.random.randint(1, 11, size=(2, 2))
mx_7 = np.random.randint(1, 11, size=(2, 3))

res_7 = np.dot(m_7, mx_7)

print(f"""Seventh task results:
First matrix
{m_7};  
Second array
{mx_7};
Result
{res_7}\n""")


Seventh task results:
First matrix
[[7 1]
 [2 2]];  
Second array
[[7 6 3]
 [1 1 6]];
Result
[[50 43 27]
 [16 14 18]]



In [9]:
#8
m_8 = np.random.randint(1, 11, size=(3, 3))

res_8 = np.linalg.inv(m_8)

print(f"""Eighth task results:
Initial matrix
{m_8};  

Inverse matrix
{res_8}\n""")

Eighth task results:
Initial matrix
[[ 8 10  7]
 [ 3  9  3]
 [ 3  2  3]];  

Inverse matrix
[[ 1.         -0.76190476 -1.57142857]
 [ 0.          0.14285714 -0.14285714]
 [-1.          0.66666667  2.        ]]



In [10]:
#9
transp_matrix = m_4.T # m_4 is a suitable matrix from the task 4
print(f"""Ninth task results:
Initial matrix
{m_4};  

T-matrix
{transp_matrix}\n""")

Ninth task results:
Initial matrix
[[0.88531463 0.83226359 0.8158358  0.7704637 ]
 [0.24096398 0.46798953 0.13975376 0.80800182]
 [0.15349897 0.09411576 0.35623085 0.12157274]
 [0.44812777 0.081343   0.14136507 0.84074688]];  

T-matrix
[[0.88531463 0.24096398 0.15349897 0.44812777]
 [0.83226359 0.46798953 0.09411576 0.081343  ]
 [0.8158358  0.13975376 0.35623085 0.14136507]
 [0.7704637  0.80800182 0.12157274 0.84074688]]



In [11]:
#10
m_10 = np.random.randint(1, 11, size=(3, 4))
a_10 = np.random.randint(1, 11, size=4)

res_10 = m_10 * a_10

print(f"""Tenth task results:
Initial matrix
{m_10}

Initial vector
{a_10}

Result
{res_10}\n""")

Tenth task results:
Initial matrix
[[ 6  9 10  2]
 [ 8  9  5  5]
 [ 2  3  8  8]]

Initial vector
[2 9 2 4]

Result
[[12 81 20  8]
 [16 81 10 20]
 [ 4 27 16 32]]



In [12]:
#11
m_11 = np.random.random((2,3))
a_11 = np.random.random((3))

res_11 = m_11 * a_11

print(f"""11th task results:
Initial matrix
{m_11}

Initial vector
{a_11}

Result
{res_11}\n""")

11th task results:
Initial matrix
[[0.31491187 0.56247708 0.44002011]
 [0.7701976  0.8453935  0.07415156]]

Initial vector
[0.1688156  0.15962983 0.90165368]

Result
[[0.05316204 0.08978812 0.39674575]
 [0.13002137 0.13495002 0.06685903]]



In [13]:
#12
m_12 = np.random.randint(1, 11, size=(2, 2))
mx_12 = np.random.randint(1, 11, size=(2, 2))

res_12 = m_12 * mx_12

print(f"""12th task results:
First matrix
{m_12};  
Second array
{mx_12};
Result
{res_12}\n""")

12th task results:
First matrix
[[ 2  2]
 [ 2 10]];  
Second array
[[6 5]
 [5 5]];
Result
[[12 10]
 [10 50]]



In [14]:
#13
# Lets use matrices from previous task
res_13 = np.dot(m_12, mx_12)

print(f"""13th task results:
First matrix
{m_12};  
Second array
{mx_12};
Result
{res_13}\n""")

13th task results:
First matrix
[[ 2  2]
 [ 2 10]];  
Second array
[[6 5]
 [5 5]];
Result
[[22 20]
 [62 60]]



In [15]:
#14
m_14 = np.random.randint(1, 101, size=(5, 5))
res_14 = m_14.sum()

print(f"""14th task results:
Matrix
{m_14}
Result
{res_14}\n""")

14th task results:
Matrix
[[37 12 46 97 83]
 [ 1 22 11 36 10]
 [32 39 86 64 75]
 [44 63  8 69 73]
 [71 23 77 80 97]]
Result
1256



In [16]:
#15
m_15 = np.random.randint(1, 11, size=(4, 4))
mx_15 = np.random.randint(1, 11, size=(4, 4))
res_15 = m_15 - mx_15

print(f"""15th task results:
First matrix
{m_15};  
Second array
{mx_15};
Result
{res_15}\n""")

15th task results:
First matrix
[[ 5  6 10  5]
 [10  6 10  5]
 [ 4  1  7  8]
 [ 3  4  3  1]];  
Second array
[[5 4 8 8]
 [8 4 5 3]
 [7 2 6 7]
 [4 6 2 7]];
Result
[[ 0  2  2 -3]
 [ 2  2  5  2]
 [-3 -1  1  1]
 [-1 -2  1 -6]]



In [17]:
#16
m_16 = np.random.random((3,3))

res_16 = np.zeros((m_16.shape[0], 1))

for i in range(m_16.shape[0]):
    for j in range(m_16.shape[1]):
        res_16[i, 0] += m_16[i, j]

print(f"""16th task results:
Matrix
{m_16}
Result
{res_16}\n""")

16th task results:
Matrix
[[0.91148858 0.47648    0.13317195]
 [0.2191822  0.2137787  0.28433359]
 [0.27524547 0.65873446 0.46175789]]
Result
[[1.52114053]
 [0.71729449]
 [1.39573782]]



In [18]:
#17
m_17 = np.random.randint(1, 11, size=(3, 4))
res_17 = m_17 ** 2

print(f"""17th task results:
Matrix
{m_17}
Result
{res_17}\n""")

17th task results:
Matrix
[[10  9  6  7]
 [ 5  3  2  4]
 [ 5  6  5  1]]
Result
[[100  81  36  49]
 [ 25   9   4  16]
 [ 25  36  25   1]]



In [19]:
#18
a_18 = np.random.randint(1, 51, size=4)
res_18 = a_18 ** 0.5

print(f"""17th task results:
Matrix
{a_18}
Result
{res_18}\n""")

17th task results:
Matrix
[16 11 25 30]
Result
[4.         3.31662479 5.         5.47722558]

